name: Checks Pipeline

on:
    workflow_call:

jobs:
    lint:
        name: 🧹 Lint / Format Check (CSharpier)
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: src
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x"

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Run CSharpier Check
              run: dotnet csharpier --check .

    static-analysis:
        name: 🔍 Static Code Analysis
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: src
        steps:
            - uses: actions/checkout@v3

            - name: Restore & Build (with analyzers)
              run: dotnet build --configuration Release /warnaserror

    security-scan:
        name: 🔐 Security Vulnerability Scan
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: src
        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Restore
              run: dotnet restore

            - name: Check for Vulnerable Packages
              run: dotnet list package --vulnerable
