name: Static Code Analysis

on:
    schedule:
        - cron: "0 0 * * 0" # Every Sunday at midnight
    workflow_dispatch:
    push:
        paths:
            - "src/**"
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - "src/**"
        branches:
            - main

jobs:
    static-analysis:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Restore & Build (with analyzers)
              run: dotnet build --configuration Release /warnaserror
